spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jsp_db?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.springboot.demo.entity


